sudo: false
language: python
cache:
  directories:
    - $HOME/.cache/pip
python:
  - "3.4"
  - "3.5"
install:
  - "pip install -r requirements.txt"
  - "pip install -r requirements_test.txt"
script:
  - "flake8 rotten_bites"
  - "py.test -v --cov rotten_bites"
after_success:
    - coveralls
